### ISSUE TITLE
all protocols being exluded

### ISSUE THREAD

**Issue by oricon** [jmtyszka/bidskit#10]
I just started to try to use bidskit and am running into some problems. The first pass runs fine with all of the data being properly converted. I modified my Protocol_Translator.json, and tried to run the second pass, but all of the protocols are excluded. Here's part of my Protocol_Translator.json file:
{
    "localizer":[
        "EXCLUDE_BIDS_Directory",
        "EXCLUDE_BIDS_Name"
    ],
    "t1_mpr_ns_sag_p2_iso":[
        "anat",
        "T1w"
    ],
    "t1_mpr_tra_iso":[
        "anat",
        "T1w"
    ],
    "ep2d_bold_moco":[
        "func",
        "task-rest_bold"
    ],
    "fMRI_Task_Learn_4":[
        "func",
        "task-learn_run-4_bold"

And this is what I'm getting when I run the second pass:
psyc311:bids_test orruser$ python ~/bidskit/dcm2bids.py -i ~/bids_test/DICOM/ -o ~/bids_test/BIDS

------------------------------------------------------------
Pass 2 : Organizing Nifti data into BIDS directories
------------------------------------------------------------

Processing subject CBLM_LEARN_101_101-CBLM
  Processing session 101_scan
* Excluding protocol ep2d_bold_moco
* Excluding protocol fMRI_Task_Control_1
* Excluding protocol fMRI_Task_Control_2
* Excluding protocol fMRI_Task_Learn_1
* Excluding protocol fMRI_Task_Learn_2
* Excluding protocol fMRI_Task_Learn_3
* Excluding protocol fMRI_Task_Learn_4
* Excluding protocol gre_field_mapping
* Excluding protocol gre_field_mapping
* Excluding protocol gre_field_mapping
* Excluding protocol localizer
* Excluding protocol localizer
* Excluding protocol localizer
* Excluding protocol t1_mpr_ns_sag_p2_iso
  Preserving conversion directory

The protocol names appear to match the json file, so I'm not sure why they're being excluded. Please let me know if I can provide any other information.

Thanks!

**Comment by jmtyszka** [comment]
Your Protocol_Translator.json file looks fine and I'm not reproducing the error with my installation. Could you post the first line of output from dcm2niix - it might be a versioning issue? Mine reads `Chris Rorden's dcm2niiX version v1.0.20170624 Clang8.1.0 (64-bit MacOS)`.

**Comment by jmtyszka** [comment]
We reproduced some protocol translator problems when using older versions of dcm2niix (2016-era) with later versions of dcm2bids.py. Let me know if updating to the latest dcm2niix version (14-July-2017, bundled with MRIcroGL) fixes this issue. Mac and Linux precompiled versions are [here](https://www.nitrc.org/projects/mricrogl/)

**Comment by oricon** [comment]
Thanks! That must have been it. I ran it at home after confirming I have
the newest release of dcm2niix and it ran completely.

Joe

--
Joseph M. Orr, Ph.D.
Assistant Professor
Department of Psychological and Brain Sciences
Texas A&M Institute for Neuroscience
Texas A&M University
College Station, TX

**Comment by jmtyszka** [comment]
Awesome! Let us know if you have further issues or feature requests.
