### ISSUE TITLE
Documentation for Injecting New Subjects into BIDS Directory

### ISSUE THREAD

**Issue by claytonjschneider** [jmtyszka/bidskit#100]
Like many others I'm sure, I have a BIDS directory of an ongoing study, and I need to be able to inject new subjects as they come along into the BIDS dataset. Without documentation to describe how to use BIDSKIT in this manner, I'm left to either try different combinations of parameters (potentially muddling a previously good BIDS dir) or reading through __main__.py and others to try to conceptualize how the parameters will work. As far as I can tell, this behavior isn't described in the documentation. 

Updating documentation to support this use case will, I think, make BIDSKIT more practical for incoming users. I started reinventing the wheel a bit to support this behavior using bash scripts (and I'm not even sure if it exists natively!) The one time I tried, I overwrote my protocol translator and participants.tsv files, I think. 

It may be that I've simply missed this in the time I've spent on the quickstart guide, but I think it would benefit all to have this use case noted in documentation, and make it clear whether bidskit does or doesn't support this use case.

**Comment by jmtyszka** [comment]
@claytonjschneider Thanks for bringing this up and its a great point. This is a common use case and one that definitely needs better documentation. bidskit supports this, but I'm still not entirely happy with the way it responds to adding new subjects/sessions to the sourcedata folder. I'm working on the development branch right now and hoping to clean up the logic and robustness of new data handling before merging back to the master branch. Should have that finished shortly, after which I'll add a clear section to the documentation.

**Comment by claytonjschneider** [comment]
Awesome! Thanks so much for getting back about this quickly @jmtyszka , this package has been thus far my favorite for working into BIDS format, for its simplicity and it being clear as it progresses. If there's anything I can contribute to this update, please let me know - I'll take a look at the development branch.

**Comment by jmtyszka** [comment]
I've merged the new dev branch which includes a WIP automatic protocol translator creator and more documentation on injecting newly acquired subject-level DICOM data into an existing BIDS dataset (https://github.com/jmtyszka/bidskit/blob/master/docs/Features.md). The trick is to use the `--subject` argument to convert only the new subject(s). As always, use the Issues tab to raise bugs, feature requests, etc.

**Comment by jmtyszka** [comment]
x
