### ISSUE TITLE
Add support for single-session data

### ISSUE THREAD

**Issue by celstark** [jmtyszka/bidskit#12]
Currently, the code mandates that there be a session directory on the input - subject/session/raw_images - and writes out a directory structure and set of filenames that have the ses-<session_label> format.  That's great if you have multiple sessions, but if you only have one session, it adds complexity and implies >1 session may exist.  BIDS has this be an optional component rather than a mandatory one, so we should set things up with that in mind.

One solution is to force placement of the DICOMs in the input folder into a "Session1" type directory, but to determine if there are >1 session folders.  If not, place the BIDS output without the session info.  The trouble here is if we're running multiple times, we may run bidskit first with "Session1" in place and then with "Session2" in place and we'd have lost the session info in the process.

A second solution is to say "sorry, you need to include session info".  Not keen on that as noted (unless I'm reading the BIDS spec wrong!).

A third solution is to take the current "loop over session directories" structure and rework it to flag the single vs. multi-session and handle accordingly.

Thoughts?

**Comment by jmtyszka** [comment]
This is something we went back and forth about at our end too, but we encounter multiple subject visits more often than most I guess. I like the idea of the code being compliant to the user's wishes on this, so how making the input DICOM directory organization dictate whether a session level will be inserted. If a session directory level is present in the DICOM directory, the BIDS source directory will also contain a session level, and the filenames will include the session key-value. Otherwise, not. I'll try to work on this next week.

**Comment by celstark** [comment]
Exactly - that's my idea.  If your DICOM has Session1 in there from the start, we roll with the assumption you want it in there in the BIDS, even if right now, it's just the one session.  If your DICOMs live in the subject-level directory, no session gets added.

Code-wise, it doesn't look too bad to add this in.

**Comment by jmtyszka** [comment]
Added --no-sessions flag (default False) to the command line args. Avoids problems with different DICOM file sources generating different heirarchies for subjects, sessions and series (eg Horus vs Osirix vs DICOM CDs, etc). Simply add this flag to the command line and dcm2bids.py won't use sessions at all. All files within a given subjects DICOM tree will be converted as though they were one session. Let me know if this works for you - I'm others will prefer this to the forced session structure.
