### ISSUE TITLE
Error "No DICOM header information found in"

### ISSUE THREAD

**Issue by adamculbreth** [jmtyszka/bidskit#132]
Hi, 

I’m trying to convert DICOMs into a valid BIDS directory structure with BIDSKIT. I get the following error:

Check dcm2nixx version
dcm2niix v1.0.20240202 detected - ok

Initializing BIDS dataset directory tree in /data/brutus_data15/adam/Effort/mri
Creating file templates required for BIDS compliance
Copying /root/miniconda3/lib/python3.12/site-packages/bidskit/templates/README to /data/brutus_data15/adam/Effort/mri/README
Copying /root/miniconda3/lib/python3.12/site-packages/bidskit/templates/CHANGES to /data/brutus_data15/adam/Effort/mri/CHANGES
Copying /root/miniconda3/lib/python3.12/site-packages/bidskit/templates/dataset_description.json to /data/brutus_data15/adam/Effort/mri/dataset_description.json
Copying /root/miniconda3/lib/python3.12/site-packages/bidskit/templates/participants.json to /data/brutus_data15/adam/Effort/mri/participants.json
Copying /root/miniconda3/lib/python3.12/site-packages/bidskit/templates/bidsignore to /data/brutus_data15/adam/Effort/mri/.bidsignore

Subjects to convert        : All
Source data directory      : /data/brutus_data15/adam/Effort/mri/sourcedata
Working Directory          : /data/brutus_data15/adam/Effort/mri/work/bidskit
Use Session Directories    : No
Overwrite Existing Files   : No
Anonymize BIDS Output      : Yes
Auto translate             : No
Bind fieldmaps             : No
GZIP compression           : o
Recon filename key         : False
Part filename key          : False
Echo filename key          : False

------------------------------------------------------------
Pass 2 : Populating BIDS directory
------------------------------------------------------------
  Creating subject list from sourcedata contents
  Found 2 subjects in sourcedata folder

------------------------------------------------------------
Processing subject M099270
------------------------------------------------------------
  Working subject directory : /data/brutus_data15/adam/Effort/mri/work/bidskit/sub-M099270
  BIDS subject directory  : /data/brutus_data15/adam/Effort/mri/sub-M099270
* No DICOM header information found in /data/brutus_data15/adam/Effort/mri/sourcedata/M099270
* Confirm that DICOM images in this folder are uncompressed
* Exiting

Other information: 

•	We recently had to reinstall bidskit and dcm2nixx following a power outage.
•	The DICOMs are not compressed and this error is occurring on DICOMs that I was able to process with bidskit using the        same protocol_translator.json file that I have currently have in the folder. 
•	We have checked the permissions in the directory to ensure that we have the proper read/write permissions
•	We have attempted to reinstall bidskit a couple of times but it doesn’t seem to change the error. 

Would be really grateful if you had any suggestions for what we might try next. 

Happy to provide additional information. 

Adam Culbreth

**Comment by jmtyszka** [comment]
Hi Adam,

Could you post the following to help debug this?

1. What version of bidskit are you running? "bidskit -V" will report this. Do you know what version you were running before the power outage?
2. What version of pydicom are you running? This is used to parse DICOM headers within sourcedata subfolders.
3. What are the contents of the /data/brutus_data15/adam/Effort/mri/sourcedata/M099270 folder and how are they organized? You could run "tree -L 2" within /data/brutus_data15/adam/Effort/mri/sourcedata

- Mike

**Comment by adamculbreth** [comment]
Hi Mike, 

I appreciate your fast response. We recently got it working. Although it began to work when using an older version of python that downloaded an older version of bidskit. I think it was a version issue but it would be good to hear the versions that you recommend. Versions for when the code wasn't working and the version that is now working are below: 

1. Bidskit: We were using  "BIDSKIT 2024.7.23”  and now we are running BIDSKIT 2023.9.7” and it’s working
2. Python: it was pydicom 3.0.0 (python3.12.2) and now we are running version is 2.4.4 (python Python 3.8.19) and it's working
3. File Structure - Structure Below: 
|-- M089223
|   `-- A6638
|       `-- SCANS
|           |-- 1
|           |-- 10
|           |-- 11
|           |-- 12
|           |-- 13
|           |-- 14
|           |-- 2
|           |-- 3
|           |-- 4
|           |-- 5
|           |-- 6
|           |-- 7
|           |-- 8
|           `-- 9

Thanks again for your help! 
Adam

**Comment by jmtyszka** [comment]
Hi Adam,

Glad you found a workaround and this makes some sense. I haven't tested bidskit with pydicom 3.0.0 yet and the API might have changed. I'll add that to the list of things to work on.

All the best,

Mike
