### ISSUE TITLE
Better handling of multiple scans with same description (e.g., multiple fMRI runs)

### ISSUE THREAD

**Issue by celstark** [jmtyszka/bidskit#14]
Right now, if multiple scans have the same DICOM description, only one of them ends up in the BIDS directory.  You can use the --use-run flag as a work-around, but then everything gets an appended number and the number is rather arbitrary.  Ideally, it should detect multiple scans with the same name and, for these, append -01 -02 or some such code.

One solution is in the pull-request I put up in #13.  I've given it a quick test on some data here and there's one tweak I may still do to it.  But, there could be other fine solutions too.  Either way, though, the current behavior of only producing one of the files is not ideal.

**Comment by jmtyszka** [comment]
Agreed. Using the series number as a run number isn't ideal and was originally intended as a temporary fix to keep things going. It should be reasonably safe to take the series number order and use that with the run- key instead as you suggest. I'll be working on this next week (including your pull request).

**Comment by celstark** [comment]
FWIW, I've pushed a few more through with the solution in the pull request and it worked smoothly enough.

**Comment by jmtyszka** [comment]
Thanks @celstark! Robust solution - pleased a lot of users at my end too.
