### ISSUE TITLE
bvec and bval files 

### ISSUE THREAD

**Issue by mainux** [jmtyszka/bidskit#16]
Hi, when I run the script with diffusion data, the bval and bvec files are not automatically generated, but if I just run the dcm2niix alone, it perfectly creates the files.

**Comment by jmtyszka** [comment]
This shouldn't be too hard to add. The current release doesn't support diffusion MRI, but the file organization is straightforward and as you point out, dcm2niix already outputs all the relevant files.

**Comment by jmtyszka** [comment]
Added support for DWI series with bval and bvec files generated by dcm2niix now copied into BIDS source tree
