### ISSUE TITLE
Multiple passes overwrite existing files

### ISSUE THREAD

**Issue by celstark** [jmtyszka/bidskit#19]
Now that we can add new subjects and re-run bidskit with the goal of just processing the new subjects, I've discovered that doing so over-writes existing subjects' data.  It's not such a huge deal for the .nii files as they should recreate the same, but tweaks to the .json files and the .tsv files certainly shouldn't be altered without asking.  (I'm currently restoring a whole bunch of *events.tsv and .json files from my backup...)

I would suggest that it check to see if the subject/session output directory exists and, if so, skips that subject/session entirely unless an "--overwrite" or "--reprocess" flag is set.  Alternatively, it could do the check on each output it's trying to make.  But, overwriting our events.tsv files is ... sub-optimal.

**Comment by jmtyszka** [comment]
Added --overwrite flag to force replacement of all sub-/ses- level images, JSON sidecars and BIDS aux files like *_task.tsv. If flag isn't present, all sub-/ses- level files are preserved. Note that source/participants.tsv will always be overwritten (to allow for new DICOM data).
