### ISSUE TITLE
handling of new subjects in dicom directory

### ISSUE THREAD

**Issue by jcrdubois** [jmtyszka/bidskit#2]
it should be possible to add a subject/session to the dicom directory, then run dcm2bids; the expected behavior would be that dcm2bids recognizes which subject/sessions have not been processed yet and processes them according to the existing Protocol_Translator.json (instead of skipping all subjects/sessions who don't have the temporary conv directory).

**Comment by jmtyszka** [comment]
ImageType string length increased to 64 characters to accommodate options of latest Siemens sequences.

**Comment by jmtyszka** [comment]
This requires a rewrite of the pass and subject/session loop logic. Might take a few days to sort this out, but will end up performing the conversion and BIDS sorting on a subject-session basis rather than what it does currently. Will update once I have some candidate code.

**Comment by jmtyszka** [comment]
Fixed by @celstark in #11
