### ISSUE TITLE
empty output with docker only

### ISSUE THREAD

**Issue by oricon** [jmtyszka/bidskit#22]
I've been running dcm2bids.py with a local installation without any trouble, but today I tried to use the docker image and my input files are not being detected so my output is empty. 

Locally I run: ~/bidskit/dcm2bids.py -i /Users/josephorr/Google\ Drive\ File\ Stream/My\ Drive/DiffusionPilot/DICOM -o /Users/josephorr/Google\ Drive\ File\ Stream/My\ Drive/DiffusionPilot/BIDS

With docker I run: docker run -it -v /Users/josephorr/Google\ Drive\ File\ Stream/My\ Drive/DiffusionPilot/DICOM/:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/source

This is my first attempt at using docker, so I'm not sure if I'm running it correctly. Thanks for any insights.

**Comment by nair-r** [comment]
Hi @oricon - this seems to be an issue in how the path to the files is specified while running the docker command. Please try the command below and let us know if that works:

docker run -it -v /Users/josephorr/Google\ Drive\ File\ Stream/My\ Drive/DiffusionPilot/:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/source

**Comment by oricon** [comment]
Hi, I tried that but still nothing unfortunately:

------------------------------------------------------------
Directory Structure
------------------------------------------------------------
DICOM Root Directory       : /mnt/dicom
BIDS Source Directory      : /mnt/source
BIDS Derivatives Directory : /mnt/derivatives/conversion
Working Directory          : /mnt/work/conversion
Use Session Directories    : Yes

------------------------------------------------------------
Pass 1 : DICOM to Nifti conversion and dictionary creation
------------------------------------------------------------

---
New protocol dictionary created : /mnt/derivatives/conversion/Protocol_Translator.json
Remember to replace "EXCLUDE" values in dictionary with an appropriate image description
For example "MP-RAGE T1w 3D structural" or "MB-EPI BOLD resting-state
---

**Comment by oricon** [comment]
Nevermind, it was an issue with my capitalizing DICOM so that /mnt/dicom was looking in the wrong place

**Comment by nair-r** [comment]
Hi - yes, that sounds right. The path should point to the root directory containing the DICOM folder as in my command above  (and not include the actual DICOM folder itself)

Glad to know it works!
