### ISSUE TITLE
Missing indent in dcm2bids.py line 279

### ISSUE THREAD

**Issue by LeaMusi** [jmtyszka/bidskit#26]
While running bidskit for the first time today I got the error message "IndentationError: expected an indented block" in line 279 of dcm2bids.py. After manually inserting this indent, everything worked fine.

**Comment by joeofco** [comment]
This was fixed in https://github.com/jmtyszka/bidskit/pull/25, but it still needs to be merged to master.

**Comment by jmtyszka** [comment]
Finally merged the fix. Apologies for the delay.
