### ISSUE TITLE
Doesn't really do the conversion?

### ISSUE THREAD

**Issue by hcp4715** [jmtyszka/bidskit#30]
Hi, Mike, 
Thanks for developing this toolbox. 
I am new to docker and python, and trying to convert my raw data from Siemens Trio 3T to bids.
I tried the docker version, and it looks good, but there are no converted files.
Below is my code and the output in the power shell.
![capture](https://user-images.githubusercontent.com/7300419/37419640-378fe726-27b5-11e8-87c3-25647ece88ec.PNG)

Actually, the folders are created, but all these folders are empty:
![capture1](https://user-images.githubusercontent.com/7300419/37419784-87b58260-27b5-11e8-972c-a9e4f7f93905.PNG)

Here is the structure of my dicom folder:
![capture2](https://user-images.githubusercontent.com/7300419/37419930-e181b41c-27b5-11e8-9c7a-02f0a806a229.PNG)

I even tried to copy the T1 and fMRI data to the session folder, but it is the same.

look forward to your reply, thanks

Best,
Chuan-Peng

**Comment by rnair07** [comment]
Hi @hcp4715 - let me look into this and update soon. There have been several new fixes and updates to the bids converter over the last few days which I'd like to incorporate into the new docker image as well. New image coming up shortly!

**Comment by jmtyszka** [comment]
Hi Chuan-Peng,

Thanks for the detailed breakdown of the issue - really appreciate the screencaps. Do you see a conversion/ subfolder in analysis/work/ and does it contain any .json or nii.gz files? Trying to work out if the dcm2niix conversion failed somehow. I've tagged @nair-r on this too - she's our container expert.

So far we've tested under Centos/Linux and OS X, but I'll extend this to Windows 7/8/10 asap to see if I can reproduce this behaviour (and fix it).

**Comment by rnair07** [comment]
Hi @hcp4715 - let me look into this and update soon. There have been several new fixes and updates to the bids converter over the last few days which I'd like to incorporate into the new docker image as well. In the meantime, same question as Mike : did it create any interim files whatsoever, such as the protocol translator in the derivatives folder?

**Comment by rnair07** [comment]
Hi @hcp4715 - could you confirm this as well: Your command mounts the path that includes 'raw_dicom' whereas your folder structure shows only '../../analysis/dicom' and not raw_dicom. Could you re-check/change the path and retry?

**Comment by rnair07** [comment]
Sorry for spamming :) Try this command: specifies the path correctly:
docker run -it -v G:\Data\coiltest\analysis:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/BIDS

This assumes all your subjects dicom are in the 'dicom' folder which is a sub-folder of 'analysis'.

**Comment by jmtyszka** [comment]
Hi @rnair07 - let me fix #29 before you update the Docker image. Should have a fix today.

**Comment by hcp4715** [comment]
Thanks so much for the quick response!

@jmtyszka in the analysis/work/ folder, there is a folder called conversion, but the conversion folder is empty; the analysis/derivative/conversion contain a .json file called "Protocol_Translator.json", but it is empty too.

@rnair07 , thanks for pointing that out, I put my raw data in analysis/dicom, tried
>  docker run -it -v G:\Data\coiltest\analysis\dicom:/mnt rnair07/bidskit --indir=/mnt/dicom --outd
ir=/mnt/BIDS
the results is the same.

**Comment by nair-r** [comment]
Hi @hcp4715 you don't actually need to specify the dicom folder when mounting, only need to specify it in the --indir flag. Use the command `docker run -it -v G:\Data\coiltest\analysis:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/BIDS` instead of `docker run -it -v G:\Data\coiltest\analysis\dicom:/mnt rnair07/bidskit --indir=/mnt/dicom --outd
ir=/mnt/BIDS`

**Comment by hcp4715** [comment]
@rnair07 great!
it works now!
![_20180314203422](https://user-images.githubusercontent.com/7300419/37426564-22f7a760-27c7-11e8-8494-ab9c1c3e69c0.png)

**Comment by nair-r** [comment]
Perfect - good to know! I'll be creating an updated docker image with additional features as per the new convertor script, so do keep an eye out for that! :)

**Comment by hcp4715** [comment]
update: the converted file was in 'work/conversion', not in BIDS

**Comment by nair-r** [comment]
Yes, post first pass conversion, the files are in the conversion folder. You then need to edit the protocol translator as per BIDS conventions and run a second pass. More info. here: https://github.com/jmtyszka/bidskit#second-pass-conversion
That puts the files in the BIDS folder.

**Comment by hcp4715** [comment]
Hi, @nair-r , 
I two addition minor issues:
first, the code for the second pass was as below on the [website](https://github.com/jmtyszka/bidskit#second-pass-conversion) :
>  docker run -it -v /PATH_TO_YOUR_RAW_DICOM_FOLDER/:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/source
If I understand correctly, the final BIDS file should be in the BIDS folder, instead of the source folder, so the 'outdir=/mnt/source' should change to 'outdir=/mnt/BIDS' if I hope to put the converted files in BIDS folder. Am I right?

Second, after I delete all the folders generated by the first pass ( because I trying to do the whole process again), and tried to run the first pass conversion again, the output showed that the protocol dictionary already exists. Only after restart docker could I re-run the first-pass.
