### ISSUE TITLE
run order not preserved

### ISSUE THREAD

**Issue by yonestar** [jmtyszka/bidskit#32]
Hi Mike,

Run order is not preserved in the latest version.  See here:

![image](https://user-images.githubusercontent.com/4513934/37673498-fd06c824-2c35-11e8-996e-03d7e83621c4.png)

The far right column shows how many volumes are in the image, so we know which file is which.  Run 13 from the first pass becomes Run 2, while Run 15 becomes Run 1. It flips.

Separately, the latest version also adds `run-01` to everything, even when there is only one run.  This could arguably be a bug, or a feature :-)  a previous version, however, did not add run number unless there was multiple runs.  I don't have much of a preference, just wanted to let you know 

Thank you!
Yoni

**Comment by jmtyszka** [comment]
I'll add some code to order the runs explicitly from the DICOM series number. I was unlucky with my test dataset, which managed to order things correctly from the file list. Expect a new commit early next week.

**Comment by jmtyszka** [comment]
Latest push fixes this issue, which was caused by lexical sorting of series number strings without zeropadding. Fix uses numerical sorting of integer series numbers.
