### ISSUE TITLE
docker conversion

### ISSUE THREAD

**Issue by tragus1** [jmtyszka/bidskit#35]
Hi,

I´m trying to convert a test data set with the docker command but I always get a empty Protocol_Translaor.json file. Can you help me with this issue?

I´m using the following comand: docker run -it -v /Users/xyz/Desktop/Converting_BIDS_test/mydicom/:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/source

folder structure of mydicoms:
-mydicoms
  -subject1
   -dcmfolder
  -subject2
   -dcmfolder

Thanks, 
Tragus

**Comment by jmtyszka** [comment]
Hi Tragus,

Try the following organization for your test study:

/Users/xyz/Desktop/Converting_BIDS_test/
- dicom/
--subject1/
---dcmfolder/
--subject2/
---dcmfolder/

Then run: docker run -it -v /Users/xyz/Desktop/Converting_BIDS_test/:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/source

Let me know if this doesn't work.
