### ISSUE TITLE
IntendedFor should include ses-XX prefix

### ISSUE THREAD

**Issue by yonestar** [jmtyszka/bidskit#37]
Hi,

Related to the issue I previously opened, but much simpler.  Also is regarding the values in the IntendedFor field in the JSON sidecar for the fmaps.  

BIDS spec requires that these values include ses-XX if the dataset has sessions.  E.g., the following is correct for datasets with multiple sessions: 
`"IntendedFor":"ses-1/func/sub-M80302134_ses-1_task-bladder_bold.nii.gz"`

bidskit currently does not prepend the ses-XX.

A simple fix that works in my testing is editting the function `bids_build_intendedfor` to have:

```splt = bids_prefix.split('_')
    # iff the bids prefix contains 'ses', prepend ses-X to the IntendedFor string                                                                                                            
    if splt[1][0:3] == 'ses':
        ifstr = os.path.join(splt[1], "func", bids_prefix + bids_suffix + ".nii.gz")
    else:
        ifstr = os.path.join("func", bids_prefix + bids_suffix + ".nii.gz")

    return ifstr
```

Am not submitting this through a pull request just yet because it may be more complicated in light of the previous issue I just opened: https://github.com/jmtyszka/bidskit/issues/36  But just wanted to bring this to your awareness now, as it relates to that previous issue

thank you!!

**Comment by jmtyszka** [comment]
Fixed in later development. Closing for now.
