### ISSUE TITLE
UnicodeDecodeError: ascii codec can't decode 

### ISSUE THREAD

**Issue by laurenbreithaupt** [jmtyszka/bidskit#38]
I have been running the bidskit previously with the docker image and need to add in new subjects. I continue to get the following error. Any advice is appreciated. 

Laurens-MBP:encode lbreithauptlangston$ docker run -it -v /Users/lbreithauptlangston/Desktop/encode/:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/source

------------------------------------------------------------
DICOM to BIDS Converter
------------------------------------------------------------
Software Version           : 1.1.1
DICOM Root Directory       : /mnt/dicom
BIDS Source Directory      : /mnt/source
BIDS Derivatives Directory : /mnt/derivatives/conversion
Working Directory          : /mnt/work/conversion
Use Session Directories    : Yes
Overwrite Existing Files   : No
Traceback (most recent call last):
  File "/app/dcm2bids.py", line 944, in <module>
    main()
  File "/app/dcm2bids.py", line 139, in main
    prot_dict = bids_load_prot_dict(prot_dict_json)
  File "/app/dcm2bids.py", line 728, in bids_load_prot_dict
    prot_dict = json.load(json_fd)
  File "/usr/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)

**Comment by nair-r** [comment]
Hi - I just tried to replicate this error (across different OS's) but was unable to do so. Could you provide more details regarding your system as well as the tree structure of your folder? Thanks.

**Comment by jmtyszka** [comment]
Presume fixed - closing.
