### ISSUE TITLE
Issue with fieldmap conversion

### ISSUE THREAD

**Issue by tragus1** [jmtyszka/bidskit#39]
When I try to convert fmaps form SIEMENS Scanner I get the following error:

docker run -it -v /home/demenzbild/Schreibtisch/TEST_HC_BIDS/:/mnt rnair07/bidskit --indir=/mnt/dicom --outdir=/mnt/source --no-sessions

------------------------------------------------------------
DICOM to BIDS Converter
------------------------------------------------------------
Software Version           : 1.1.1
DICOM Root Directory       : /mnt/dicom
BIDS Source Directory      : /mnt/source
BIDS Derivatives Directory : /mnt/derivatives/conversion
Working Directory          : /mnt/work/conversion
Use Session Directories    : No
Overwrite Existing Files   : No

------------------------------------------------------------
Pass 2 : Populating BIDS source directory
------------------------------------------------------------
    Creating new dataset_description.json

------------------------------------------------------------
Processing subject TAURESTHCm002007S4620
------------------------------------------------------------
  BIDS working subject directory : /mnt/work/conversion/sub-TAURESTHCm002007S4620
  BIDS source subject directory  : /mnt/source/sub-TAURESTHCm002007S4620
* Excluding protocol Perfusion_Weighted
* Excluding protocol Axial_3TE_T2_STAR
* Excluding protocol Axial_MB_rsfMRI_(Eyes_Open)
* Excluding protocol Axial_MB_DTI
* Excluding protocol Sagittal_3D_FLAIR
  Organizing Field_Mapping
    Identifying fieldmap image type
    GRE detected
    Identifying magnitude and phase images
    Echo 1 magnitude
  Populating BIDS source directory
    Copying 007_S_4620--Field_Mapping--GR--9_e1.nii.gz to sub-TAURESTHCm002007S4620_run-01_task-rest_magnitude.nii.gz
* Excluding protocol Axial_3TE_T2_STAR
* Excluding protocol Axial_3TE_T2_STAR
  Organizing Field_Mapping
    Identifying fieldmap image type
    GRE detected
    Identifying magnitude and phase images
Traceback (most recent call last):
  File "/app/dcm2bids.py", line 944, in <module>
    main()
  File "/app/dcm2bids.py", line 233, in main
    bids_run_conversion(work_conv_dir, first_pass, prot_dict, bids_src_ses_dir, SID, SES, overwrite)
  File "/app/dcm2bids.py", line 353, in bids_run_conversion
    overwrite)
  File "/app/dcm2bids.py", line 437, in bids_purpose_handling
    TE1, TE2 = bids_fmap_echotimes(work_json_fname)
  File "/app/dcm2bids.py", line 758, in bids_fmap_echotimes
    mag1_ser_no = str(int(ser_no) - 1)
ValueError: invalid literal for int() with base 10: '10_e2_ph'

Can you help me with that?
All the other sequences are correctely converted when I exclude the fmaps.

Thanks,
balotay

**Comment by jmtyszka** [comment]
This looks like dcm2niix has added a "_ph" suffix to the converted filename, which may be a new feature (it's changing rapidly right now, which is a two-edged sword). For the record, which version of dcm2niix are you using?

**Comment by rnair07** [comment]
It looks like the latest docker container was used which uses dcm2niix version 28-Mar-2018 (v1.0.20180328).

**Comment by rnair07** [comment]
I see we have a new dcm2bids script v.1.1.2. Will rebuild the docker with this script and push shortly.

**Comment by jmtyszka** [comment]
I've pushed a fix to dcm2bids.py which works with dcm2niix v1.0.20180404 (latest git release). The "_e2_ph"-style suffix was added recently and wasn't being handled correctly by the fieldmap handler in dcm2bids.py. Should all work now, we just need to update the docker container.

**Comment by nair-r** [comment]
Cool. Just pushed a new docker build to the hub  - built with dcm2bids.py v1.1.2 and dcm2niix v1.0.20180404. 
Re-running the BIDS conversion should automatically pull the newer image. Cheers!

**Comment by jmtyszka** [comment]
Thanks @rnair07!
