### ISSUE TITLE
.gz files not actually gzipped

### ISSUE THREAD

**Issue by zanderso13** [jmtyszka/bidskit#46]
Hello!

I've been having a strange problem running bidskit on my data that I wasn't sure how to deal with. It appears that files are being renamed with the .gz extension but they are not actually being compressed. I run into this problem after running bidskit for the second time when files appear in my final bids directory. Do you have any guidance on what might be causing this issue? 

Thank you!

**Comment by jmtyszka** [comment]
I'd start by checking your installation of dcm2niix, which is handling the compression. Which version are you using? This [line](https://github.com/jmtyszka/bidskit/blob/master/dcm2bids.py#L228) includes the -z flag so the instruction is going out to compress output images.

**Comment by zanderso13** [comment]
I just downloaded dcm2niix from the link posted on the main github page (v 2.1.43).  Is there a different version I should be using?

**Comment by jmtyszka** [comment]
That's a strange version number. If you run dcm2niix without argument from the command line, you should see the version in the second line of output. eg

> $ dcm2niix
> Compression will be faster with 'pigz' installed http://macappstore.org/pigz/
> Chris Rorden's dcm2niiX version v1.0.20180622 Clang10.0.0 (64-bit MacOS)
> usage: dcm2niix [options] <in_folder>

In my case (on a mac) I have version v1.0.20180622 which I believe is the latest stable release.

Try running dcm2niix manually with the -z option on folder containing a DICOM series and see whether the output is gzipped.

**Comment by zanderso13** [comment]
Thank you! I've confirmed I have this same version. I am running what you suggested now and will let you know how it goes!

**Comment by zanderso13** [comment]
I ran dcm2niix successfully using the options you mentioned above. Should I explore the other options to see if any of those reproduce the error I'm getting?

**Comment by jmtyszka** [comment]
Yes, that would be a good plan. Let us know if reproducing the dcm2niix command with all options works from the command line but not when called from within dcm2bids.
