### ISSUE TITLE
run order not preserved

### ISSUE THREAD

**Issue by yonestar** [jmtyszka/bidskit#48]
Hi Mike,

We finished data collection and are using bidskit again. I am still seeing the behavior that run order is not always preserved by bidskit, as in #32 . For example:

In the dicom dir, I have:
```    
joas2631@blogin01:$ ls acute_pa_32ch_mb8_v01_r01_0023/|wc
    109     109    2616  
joas2631@blogin01:$ ls acute_pa_32ch_mb8_v01_r01_0025/|wc
    816     816   19584
```

So 109 volumes for series 23, and 816 volumes for series 25 (there was a problem w/ the run and we had to start it over part-way through) -- the order switches!.

But in the bids directory created by bidskit, I see:
```
joas2631@blogin01:$ lsi sub-M80371745/ses-1/func/*nii
sub-M80371745/ses-1/func/sub-M80371745_ses-1_task-acute_run-01_bold.nii        82   82   56  816
sub-M80371745/ses-1/func/sub-M80371745_ses-1_task-acute_run-02_bold.nii        82   82   56  109
```

So the 109 volume run becomes `run-02`, while the 816 volume run becomes `run-01`.

I am using the latest version (1.1.2).

If it would be helpful to provide the data, glad to - just lmk

thanks!
Yoni Ashar

**Comment by yonestar** [comment]
just a follow up note in case its helpful. Was talking w/ a fellow bidskit user, and I now believe that this is only an issue when the the same run happens twice, for some unplanned reason (e.g. technical error, participant-related issue). When the same task is intended to be run twice, and ProtocolTranslator appropriately labels them as `run-01` and `run-02`, there will not be a problem. So just seems to be when you need to run the same task twice due to some error.

**Comment by jmtyszka** [comment]
Thanks, this is actually quite helpful. I'm planning on doing another pass on bidskit development in the next couple of weeks and will add some code to try to catch this situation. There is some argument for deleting failed runs from the DICOM folder prior to running bidskit, but that's only practical if your DICOM folder organization has series-level subfolders (ie not a flat organization).

**Comment by jmtyszka** [comment]
The issue may have been the arbitrary ordering of the list returned by glob, as described [here](https://stackoverflow.com/questions/6773584/how-is-pythons-glob-glob-ordered). The list is now lexically sorted before being passed to run number generation. Let me know if this fixes things for you.
