### ISSUE TITLE
NifTI files erroneously skipped when "* JSON sidecar not found" due to premature termination of a for loop

### ISSUE THREAD

**Issue by AnonymousBoba** [jmtyszka/bidskit#50]
I am using v1.1.2; I see the same issue using both the docker container and the source script. I'm having an issue where some files which are correctly recognized on the first pass (based on the console output, the protocols for that subject are being added to the dictionary), but then are omitted in the second pass in assembling the BIDS data set. This appears to be due to a small logical error in dcm2bids.py.

If the ith file in the list of NifTI filelist has no JSON sidecar, then the for loop iterating over the filelist should move onto the next iteration of the for loop. Instead, it is prematurely breaking the loop entirely.

More specifically, I believe `break` should be `continue` in the following code section

                if not os.path.isfile(src_json_fname):
                    print('* JSON sidecar not found : %s' % src_json_fname)
                    break

In particular, I believe this happens when the ith file is the \*_ADC.nii.gz" file being generated by dcm2niix for DWI files. It is creating both a "\*.nii.gz" image and an "\*_ADC.nii.gz"; the former has a corresponding JSON file but the latter does not, causing the for loop to be prematurely terminated due to a lack of a corresponding JSON sidecar. All of the NifTI files that come after that  "\*_ADC.nii.gz" file within the filelist (`enumerate(filelist)`) fail to be transferred over to the BIDS data set.

Apologies if I have made any mistakes in this.

**Comment by jmtyszka** [comment]
Thanks for bringing this issue up. Your suggest logic fix works well and has been implemented in v1.1.3. Let me know if this doesn't fix the issue at your end.
