### ISSUE TITLE
source & derivatives naming scheme

### ISSUE THREAD

**Issue by jcrdubois** [jmtyszka/bidskit#52]
I wonder if it would make more sense to change the naming scheme of the various folders, so that the final folder structure in the dataset is more BIDS-like. From the BIDS specification, eventually the dicoms should go in a folder called "sourcedata". The BIDS-compliant subjects/sessions should be at the top level of the dataset directory. I would also suggest to move the "Protocol_Translator.json" from derivatives/conversion to the "code" folder. Here is what this would look like:

myDataset

(INPUT FOR BIDSKIT dcm2bids.py)
- sourcedata
    - sub-myFirstSub
        - ses-myFirstSes
            - firstDicomSeries
            ....
            - lastDicomSeries
        ...
    ...
    - sub-myLastSub
        - ses-myFirstSes
        ...

(OUTPUTS OF BIDSKIT dcm2bids.py)
- derivatives
    (empty)
- working
    (outputs of dcm2niix, temporary)
- code
    - Protocol_Translator.json
- sub-myFirstSub
    - ses-myFirstSes
    ...
...
- sub-myLastSub
    - ses-myFirstSes
    ...
- participants.tsv
- dataset_description.json

**Comment by jmtyszka** [comment]
Thanks @jcrdubois - I'll take a look at the BIDS v1.2 specification and will update the output organization accordingly. I think I'm still stuck at v1.1.

**Comment by jmtyszka** [comment]
I'm going to migrate the output folder directory structure for bidskit so that it tracks the organization described by [the BIDs Starter Kit](https://github.com/bids-standard/bids-starter-kit/wiki/The-BIDS-folder-hierarchy). At the time of writing, this represents BIDS v1.2.
