### ISSUE TITLE
Error with first pass

### ISSUE THREAD

**Issue by bryjack0890** [jmtyszka/bidskit#58]
Hi, I'm running the following command:

docker run -it -v /Users/bryanjackson/Project/:/STERN jmtyszka/bidskit -d /STERN 

and receive the following error: 

node: bad option: -d

My folder is structured like this:

Project/sourcedata/subjs/DICOMS

I've rebuilt the container already and am still receiving the error.

**Comment by LeoCeravolo** [comment]
Hi,
same problem here... using the exact same command.
Soes anyone know why we get this issue?

Thanks,
Leo

**Comment by jmtyszka** [comment]
Sorry I've been sluggish to get to this error. I'll be able to look into this early next week and will update.

**Comment by LeoCeravolo** [comment]
Hi,


okay that's cool thanks a lot!


Best,

Leo

________________________________
De : Mike Tyszka <notifications@github.com>
Envoyé : mercredi, 20 novembre 2019 00:36:49
À : jmtyszka/bidskit
Cc : Léonardo Ceravolo; Comment
Objet : Re: [jmtyszka/bidskit] Error with first pass (#58)


Sorry I've been sluggish to get to this error. I'll be able to look into this early next week and will update.
