### ISSUE TITLE
subject flag

### ISSUE THREAD

**Issue by doritdorit** [jmtyszka/bidskit#59]
**Is your feature request related to a problem? Please describe.**
not really a problem, more a convenience to run single subjects in the sourcedata folder (instead of all of them).

**Describe the solution you'd like**
Addition of subject flag (e.g. -s SUBJECT01) when calling bidskit to specify which subject in sourcedata folder to convert.

**Comment by bogpetre** [comment]
Had the same need the other day. I've put together what I think is a patch. It seems to be working for second pass runs but still needs some testing. Perhaps it may help as a start if nothing else.

[subj_opts.txt](https://github.com/jmtyszka/bidskit/files/3882045/subj_opts.txt)

**Comment by jmtyszka** [comment]
Later development of --subject argument likely addressed this. Closing for now.
