### ISSUE TITLE
bidskit 1.2.3 not completing 1st pass file conversions

### ISSUE THREAD

**Issue by idroberts** [jmtyszka/bidskit#60]
When I run bidskit 1.2.3 it creates the directories but does not complete the DICOM to Nifti conversion. There are no warnings or errors given. It creates the work, derivatives, and sourcedata folders, but they are all empty. The code folder contains a Protocol_Translator.json, but the file is empty. Any ideas why this might be the case?

Terminal output:

------------------------------------------------------------
BIDSKIT 1.2.3
------------------------------------------------------------

dcm2niix version v1.0.20190720 detected
Initializing BIDS dataset directory tree in /Volumes/My_Passport/test
Creating required file templates
    Creating new dataset_description.json
    Creating new participants.json

Source data directory      : /Volumes/My_Passport/test/sourcedata
Working Directory          : /Volumes/My_Passport/test/work
Use Session Directories    : Yes
Overwrite Existing Files   : No

------------------------------------------------------------
Pass 1 : DICOM to Nifti conversion and translator creation
------------------------------------------------------------

---
New protocol dictionary created : /Volumes/My_Passport/test/code/Protocol_Translator.json
Remember to replace "EXCLUDE" values in dictionary with an appropriate image description
For example "MP-RAGE T1w 3D structural" or "MB-EPI BOLD resting-state
---

Subject directories to prune:

**Comment by jmtyszka** [comment]
How is your DICOM data organized in the sourcedata/ directory? You should have at least one subject folder in there, containing at least one session directory. See the Quick Start guide here: https://github.com/jmtyszka/bidskit/blob/master/docs/QuickStart.md.

If your already have a subject/session organization for your DICOM files in the sourcedata/ directory let me know and we can continue debugging from there.

**Comment by idroberts** [comment]
Oh I see! I just updated to the latest version and was missing the fact that the required organization for the DICOM data had changed. Thanks!
