### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by hippocampo** [jmtyszka/bidskit#62]
After upgrading to the latest Bidskit, I believe I messed something up.  I've attempted reinstallation via several different methods but keep getting an error when running it, similar to the following:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/bidskit", line 11, in <module>
    load_entry_point('bidskit==1.2.3', 'console_scripts', 'bidskit')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bidskit/launcher.py", line 207, in main
    args.clean_conv_dir, overwrite)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bidskit/organize.py", line 68, in organize_series
    run_no = btr.auto_run_no(nii_list, prot_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bidskit/translate.py", line 360, in auto_run_no
    _, bids_suffix, _ = prot_dict[info['SerDesc']]
KeyError: '3-PLANE_LOC'

It doesn't seem to recognize the naming convention of the NIFTI files.  If I delete those dicoms, it throws an error for a different file.  Any thoughts/help would be greatly appreciated!  Thank you.

**Comment by jmtyszka** [comment]
It looks like the series description '3-PLANE_LOC' isn't present in your Protocol_Translator.json dictionary. The string '3-PLANE_LOC' is being pulled from the JSON sidecar generated by dcm2niix and should have made its way into Protocol_Translator.json during the first pass conversion. Maybe check to see if it's there (or post your Protocol_Translator.json file here).

**Comment by hippocampo** [comment]
Mike, thanks so much.  I am feeling sheepish for making such an error; I rebuilt the protocol translator, updated it, and it now works fine.  Thanks again for taking the time to help, it's a terrific and incredibly useful script!

**Comment by jmtyszka** [comment]
@hippocampo No worries at all - in fact your comment helps us. I'll add a more descriptive handler for this error to help users spot missing keys in the Protocol_Translator dictionary. Glad you like the script!
