### ISSUE TITLE
clarification on sourcedata requirements

### ISSUE THREAD

**Issue by dmd** [jmtyszka/bidskit#67]
I'm confused by what sourcedata requirements there are. I have:

```
sourcedata
└── 027
    ├── fieldmap_BOLD_1
    ├── fTRT_1
    ├── Localizers_1
    ├── MPRage_1
    ├── PresentationStates_1
    ├── Survey_1
    ├── unnamed_1
    └── ZShimRef_1
```

(each of those contains a bunch of dicom images).

Those are the names the scanner gives those directories.  Do I have to rename them in order to use bidskit? 

```
------------------------------------------------------------
Processing subject 027
------------------------------------------------------------
* Looking at Localizers_1
* Subject/session names cannot contain "-" or "_"
* Please rename the subject/session folder in the sourcedata directory and rerun bidskit
```

**Comment by jmtyszka** [comment]
Bidskit should be able to handle "-" and "_" following the resolution of Issue #61. Let me check what's happening with the docker container (I'm assuming you're using Docker to run bidskit based on your other comments). One possible workaround (I haven't tested this) would be to place all the series directories (fieldmap_BOLD_1, etc) within a dummy session directory called "1". The underscore check only applies to the subject and session names, not the series names. The final subject data structure would then be sub-027/ses-1/... and filenames would include "_ses-1_".

**Comment by dmd** [comment]
I was not able to get the Docker version to work at all -- the above is using the pip install version.

**Comment by dmd** [comment]
Oh - I am not using sessions. I was under the impression that [sessions are optional](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#single-session-example).

**Comment by jmtyszka** [comment]
The pip version is still at 1.2.3. Will try to get that updated today. Are you able to install bidskit using setup.py in your environment?

**Comment by dmd** [comment]
Yeah. It's just the Docker version that fails.

**Comment by jmtyszka** [comment]
The PyPi version has been updated to 2019.8.16 - let me know if that works out of the box. I'll be looking at the Docker issues today.

**Comment by jmtyszka** [comment]
You're also correct that sessions are optional in the BIDS specification. bidskit assumes sessions by default, but can run without session handling using the --no-sessions flag.

**Comment by dmd** [comment]
Ok, apparently `--no-sessions` is all I needed for this one.
