### ISSUE TITLE
DICOMDIR as input

### ISSUE THREAD

**Issue by alexsayal** [jmtyszka/bidskit#71]
Hello,

I have a dataset from a Philips scanner which is in DICOMDIR format. Is this anyway compatible with bidskit or is there any conversion you know which can make it work?

I tried placing the DICOMDIR as sourcedata but no series are identified in Protocol_Translator.json.

Thank you in advance,

**Comment by jmtyszka** [comment]
I'm not planning on implementing DICOMDIR support at this point. If anyone feels this is essential I'd encourage them to fork the repo and generate a pull request. Closing for now.
