### ISSUE TITLE
run- label issue with anat-entity.

### ISSUE THREAD

**Issue by JasonProtoMe** [jmtyszka/bidskit#72]
Hi Mike,

**Describe the bug**
I believe I've come across a BIDS convention error during your conversions. For directories under the 'anat' entity, the labels are limited to subject (sub-), session (ses-), acquisition (acq-), contrast enhancing agent (ce-), and reconstruction (rec-). However, I think the bidskit program creates a run- label for all .nii files, if it doesn't start with 'EXCLUDE' in the protocol_description.json, during the non-first conversion. This is also apparent in your QuickStart guide, under the 'Editing the Translator Dictionary', second image. 

**My concept solution**
I can see that the run-* key gets added BIDS suffix in organize.py line 113 and for the intendedFor field in line 116. If we simply have those in an if-statement, we could get around it:
` if prot_dict[info['SerDesc']][0] not in ['anat', 'beh']: `
`      bids_suffix = btr.add_run_number(bids_suffix, run_no[fc]) `
`      prot_dict = btr.add_intended_run(prot_dict, info, run_no[fc]) `

**Additional context**
Getting BIDS entity/label information from:
https://bids-specification.readthedocs.io/en/latest/99-appendices/04-entity-table.html

Please let me know what you think or if I've missed something.

Thank you,

Jason

**Comment by jmtyszka** [comment]
Auto run number greatly improved in 2022.8.25 using DICOM header fields rather than dcm2niix filenames.
