### ISSUE TITLE
Flag on initial run without sourcedata directory

### ISSUE THREAD

**Issue by davekahn** [jmtyszka/bidskit#74]
On the initial run of bidskit, if the directory structure does not include a sourcedata directory (e.g. if all subject directories are on the level where bidskit -d was pointed, no flag is raised. The code runs quickly and creates a lot of empty files. 

It would be more functional to have bidskit throw back a flag that the sourcedata directory was not found or was empty, and ask the user to confirm to proceed (or similar).

**Comment by jmtyszka** [comment]
Added check for sourcedata folder in dataset directory. Running bidskit without a sourcedata containing DICOM data doesn't make much operational sense, even for pre-filling an empty bidskit tree. Current behavior now throws an error message asking for sourcedata to be created and filled, then exists.
