### ISSUE TITLE
Issues with BOLD SBRefs

### ISSUE THREAD

**Issue by davekahn** [jmtyszka/bidskit#75]
When running the second round of bidskit, there seems to be an issue for BOLD runs whose filenames do not already contain the _run flag. For single runs, a _run-01 will be added to the filename, but it is added to a different location in the filename for the SBRef and the full EPI:
<prefix>_run-01_bold.nii.gz
<prefix>_bold_run-01_sbref.nii.gz
It seems that fMRIprep has difficulty recognizing these as paired files. 

Also with SBRefs - it seems fMRIprep is case sensitive with the _sbref suffix - having a catch flag if a Protocol_Translator.json file sorts files with a _SBRef or alternative suffix might be helpful for avoided errors.

**Comment by jmtyszka** [comment]
Later development, particularly the --auto argument does a much better job of handling the Siemens recon suffices, particularly SBRef (from the CMRR multiband sequence) and RMS (from the MGH morphology MEMPRAGE). Closing for now.
