### ISSUE TITLE
Passing custom options to dcm2niix

### ISSUE THREAD

**Issue by alexenge** [jmtyszka/bidskit#79]
**Is your feature request related to a problem? Please describe.**
As of now, bidskit calls dcm2niix with some default command line flags to do the conversion. However, in some cases users might want to deviate from some of these options. For example, the compression of the `.nii` files is a lot faster with the (non-default) `-z i` flag than with the (default) `-z y` flag when running the conversion on a high-performance computing (HPC) cluster (see this discussed, e.g., [here](https://github.com/rordenlab/dcm2niix/issues/104#issuecomment-307148805), [here](https://github.com/rordenlab/dcm2niix/issues/361#issuecomment-559227729), and [here](https://github.com/rordenlab/dcm2niix/issues/342#issuecomment-539139873)).

**Describe the solution you'd like**
Alternative tools like dcm2bids and heudiconv allow users to pass custom options to dcm2niix via custom `.json` files (see [the `"dcm2niixOptions"` field in the `dcm2bids_config.json` file for dcm2bids](https://unfmontreal.github.io/Dcm2Bids/docs/4-advance/#dcm2niixoptions) and [the `--dcmconfig` flag for heudiconv](https://heudiconv.readthedocs.io/en/latest/usage.html#Named%20Arguments)). Maybe such custom dcm2niix options could also be enabled in bidskit as part of the `Protocol_Translator.json` file (following the dcm2bids approach) or by allowing users to specify a new `.json` file just for this purpose (following the heudiconv approach).

**Describe alternatives you've considered**
Using one of these other tools (although we prefer bidskit because it's generally a lot faster); running the conversion in bidskit with the default options (which is somewhat slow on our HPC because of `-z y`).

**Additional context**
Thanks a lot for this super useful tool (and, hopefully, for considering this request).

**Comment by jmtyszka** [comment]
Added command line option to pass gzip compression options to dcm2niix
