### ISSUE TITLE
Add support for fieldmap IntendedFor JSON field

### ISSUE THREAD

**Issue by jmtyszka** [jmtyszka/bidskit#8]
Allowing linking of fieldmaps to associated EPI data through the Protocol_Translator.json file. Required by fmriprep, etc.

**Comment by celstark** [comment]
Was just about to post this -- thanks!

**Comment by yonestar** [comment]
Hi @jmtyszka thank you for this wonderful tool.  We are starting to use this now in Tor Wager's lab (CU Boulder).  This open issue here is something we need in place to fully use this tool.  I was wondering whether you have started work on it, or whether we should take a crack at it?  We haven't  worked with the BIDSKit source code yet, so there might be a learning curve, and at the same time we are glad to contribute to this tool.  Let me know what you think. Thanks, Yoni

**Comment by jmtyszka** [comment]
Working on this (and a few other feature requests and enhancements) right now. Should have an update to the master branch later today.

**Comment by jmtyszka** [comment]
Support for IntendedFor key with single or multiple file links added.

**Comment by celstark** [comment]
Don't these need to become something like:
ses-Session1/func/sub...
rather than:
sub...
