### ISSUE TITLE
Installation told me to ask for help?

### ISSUE THREAD

**Issue by katedamme** [jmtyszka/bidskit#85]
**Describe the bug**
During installation (after downloading and sudo python3 setup.py install) I received the following message:

```
Running docopt-0.6.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gb4c7u30/docopt-0.6.2/egg-dist-tmp-igtxp_0g
error: Setup script exited with error: SandboxViolation: mkdir('/private/var/root/Library/Caches/com.apple.python/private', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

**To Reproduce**
1. sudo python3 setup.py install
2. Likely local computer specific issue that I am looking for advice on 

**Expected behavior**
Seems to have failed installing properly, and provided the following error message. 
Please send troubleshooting advice or manual instructions for installation.
bidskit testing showed that it is not installed properly

```
Running docopt-0.6.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gb4c7u30/docopt-0.6.2/egg-dist-tmp-igtxp_0g
error: Setup script exited with error: SandboxViolation: mkdir('/private/var/root/Library/Caches/com.apple.python/private', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

**Desktop (please complete the following information):**
 - Browser : chrome
 - Version : bids kit version 1.2.1; python3 version 3.8.2; dcm2niix version v1.0.20190902

**Comment by jmtyszka** [comment]
Apologies for the slow response. This looks like a permissions issue for easy_install. Make sure you have the latest version of bidskit and try running
