### ISSUE TITLE
Issue with 'Intended for' field

### ISSUE THREAD

**Issue by tstoica** [jmtyszka/bidskit#86]
In the “protocol_translator.json” file, I have a fieldmap file that I collected, and I placed the bold files needed for correction in the “intended for” field. I am using fmriprep for my preprocessing, but unfortunately fmriprep isn't using the fieldmap for correction. Is it a syntax issue? Any help would be appreciated !

{
“DTI_64_DIRs_GRAPPA2”:[
“EXCLUDE_BIDS_Directory”,
“EXCLUDE_BIDS_Name”,
“UNASSIGNED”
],
**“gre_field_mapping_NET”:[
“fmap”,
“acq-bold”,
[“task-rest_bold”, “task-ta2_bold”, “task-ta1_bold”]
],**
“Rest_3mmiso_minTR2_2”:[
“func”,
“task-rest_bold”,
“UNASSIGNED”
],
“TA2_3mmiso_minTR2_2”:[
“func”,
“task-ta2_bold”,
“UNASSIGNED”
],
“TA_3mmiso_minTR2_2”:[
“func”,
“task-ta1_bold”,
“UNASSIGNED”
],
“MPRAGE”:[
“anat”,
“T1w”,
“UNASSIGNED”
]
}

**Comment by dkp** [comment]
“gre_field_mapping_NET”:[
“fmap”,
“acq-bold”,
[“task-rest_bold”, “task-ta2_bold”, “task-ta1_bold”]
],

You should probably NOT have "acq-bold" in the fieldmap name.  Instead, leave the fieldmap name as a single space enclosed in double-quotes:

Here's my working example:
 "field_mapping":[
        "fmap",
        " ",
        ["task-rest_run-01_bold", "task-rest_run-02_bold"]
    ],

Now I've got the same sort of problem with the reverse-phase-encode image.  ; (

**Comment by jmtyszka** [comment]
Latest version supports automatic binding of fieldmaps based on closest fmap in time to the start of each BOLD series. Should handle syntax issues like this for most use cases. Let me know if it doesn't.

**Comment by dkp** [comment]
Thanks so much!
