### ISSUE TITLE
Problem adding new participant

### ISSUE THREAD

**Issue by celstark** [jmtyszka/bidskit#9]
I've got data in raw_data/s2/Day1/*IMA and I run `./dcm2bids.py -i ../raw_data_SS -o ../BIDS_SS`, edit my ProtocolTemplate.json, run it again, and everything works just fine.

I now copy into raw_data/s1/Day1/*IMA and run again, but it's not doing what I expect.  I hit Pass 2 only (expected) and for the new participant, it just says "Processing session Day1" and "Preserving conversion directory".  It goes on to organize the one it already did.

I've replicated this several times now.  I let it process s1 and s2 at once, organize all just fine, and then added in s3.  It skips over s3 with just the "Preserving conversion directory" and re-organizes s1 and s2.

Am I missing something in how to add in new subjects?

**Comment by celstark** [comment]
OK - looking at the code - line 140 (ver 0.9.3) is `if first_pass` ... run dcm2nixx.  But `first_pass` is only true when you don't have any ProtocolTemplate.  You have one as soon as you've run one person.  Don't we need a different logic here to see if this (new) subject needs dcm2nixx?

**Comment by jmtyszka** [comment]
This is similar to a previous feature request to allow adding subjects to the dicom folder and rerunning conversion to add the subject's data to an existing BIDS source tree. Will bump this up and get a fix out for this shortly.

**Comment by celstark** [comment]
Haven't worked with github oddly enough, but I've created a fork with a potential simple solution to this.

**Comment by jmtyszka** [comment]
Hi @celstark. Thanks for this elegant solution! Once you're happy with your changes, go ahead and make a pull request and I'll integrate your changes into the master branch.
