### ISSUE TITLE
Adding key to structural scan filenames to indicate bias correction

### ISSUE THREAD

**Issue by sarahoh** [jmtyszka/bidskit#90]
We noticed that bidskit treats bias-corrected structural scans as separate runs (e.g. original T1w gets labeled with "run-01", while the bias-corrected T1w with "NORM" in image type gets labeled with "run-02"; see screenshots below).
![thumbnail_image (1)](https://user-images.githubusercontent.com/22419061/151907090-d7842c4a-28fc-4053-8ba9-9d060b4aa799.png)
![thumbnail_image](https://user-images.githubusercontent.com/22419061/151907106-2ebefb54-dc9a-49be-8acf-96a966eb5d73.png)

If possible, could you add a “recon-<recon type>” key in the BIDS filenames to indicate whether a structural has been bias corrected?

Thanks so much!

**Comment by jmtyszka** [comment]
Yes, definitely should be doable. I'll add this as a command line argument control with the default being off and no recon- key generated. You can switch it on as required.

**Comment by jmtyszka** [comment]
Version 2022.2.10 now supports complex-valued images (part-* filename key), multiecho BOLD (echo-*) and bias correction mode (recon-*).
