### ISSUE TITLE
TypeError: can only concatenate list (not "str") to list

### ISSUE THREAD

**Issue by jawaltz** [jmtyszka/bidskit#96]
Hi-

I replaced my blank Protocol Translator with what I thought was a sensible one, but I got the error above.

There are two elements of my Protocol Translator file that may be causing problems:
1. We obtained two anatomies, both labeled "T1w_MPR_1"; I specify the translation as:

    "T1w_MPR_1":[
        "anat",
        ["run-01_T1w", "run-02_T1w"],
        "UNASSIGNED"
    ]

2. AP_SBRef files get used both as fieldmaps ("_epi") and func images ("_sbref"). I translate those files twice; is that correct?

    "cmrr_mb4_bold_566_CBT_Run5_AP_SBRef":[
        "fmap",
        "dir-AP_run-05_epi",
        "task-CBT_acq-AP_run-05_bold"
    ],
    "cmrr_mb4_bold_566_CBT_Run5_AP_SBRef":[
        "func",
        "task-CBT_acq-AP_run-05_sbref",
        "UNASSIGNED"
    ],

In any case, my translation doesn't work at all; nifti files don't have the right names, and they don't end up in the right folders. 

I have a file called "Protocol_Translator.json" in the "code" subfolder. Is that not where it is supposed to be?

Thanks,

Jim Waltz

**Comment by jmtyszka** [comment]
Hi @jawaltz Thanks for raising this issue - I'll try to sort out what's going on an offer some workarounds.

**Comment by jawaltz** [comment]
Hi-

Thanks for responding.

I changed the Protocol Translator file as instructed, and I no longer get the error, but the files still do not appear to be properly renamed or in the right location.

I tried to attach the new Protocol Translator file, but it wouldn't let me.

These are the output file names I get:

N14857--cmrr_mb4_bold_318_CBT_Run1_PA--EP--36.json
N14857--cmrr_mb4_bold_318_CBT_Run1_PA--EP--36.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run1_PA_SBRef--EP--35.json
N14857--cmrr_mb4_bold_318_CBT_Run1_PA_SBRef--EP--35.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run2_PA--EP--40.json
N14857--cmrr_mb4_bold_318_CBT_Run2_PA--EP--40.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run2_PA_SBRef--EP--39.json
N14857--cmrr_mb4_bold_318_CBT_Run2_PA_SBRef--EP--39.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run3_PA--EP--44.json
N14857--cmrr_mb4_bold_318_CBT_Run3_PA--EP--44.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run3_PA_SBRef--EP--43.json
N14857--cmrr_mb4_bold_318_CBT_Run3_PA_SBRef--EP--43.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run4_PA--EP--48.json
N14857--cmrr_mb4_bold_318_CBT_Run4_PA--EP--48.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run4_PA_SBRef--EP--47.json
N14857--cmrr_mb4_bold_318_CBT_Run4_PA_SBRef--EP--47.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run5_PA--EP--52.json
N14857--cmrr_mb4_bold_318_CBT_Run5_PA--EP--52.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run5_PA_SBRef--EP--51.json
N14857--cmrr_mb4_bold_318_CBT_Run5_PA_SBRef--EP--51.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run6_PA--EP--56.json
N14857--cmrr_mb4_bold_318_CBT_Run6_PA--EP--56.nii.gz
N14857--cmrr_mb4_bold_318_CBT_Run6_PA_SBRef--EP--55.json
N14857--cmrr_mb4_bold_318_CBT_Run6_PA_SBRef--EP--55.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run1_AP--EP--34.json
N14857--cmrr_mb4_bold_566_CBT_Run1_AP--EP--34.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run1_AP_SBRef--EP--33.json
N14857--cmrr_mb4_bold_566_CBT_Run1_AP_SBRef--EP--33.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run2_AP--EP--38.json
N14857--cmrr_mb4_bold_566_CBT_Run2_AP--EP--38.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run2_AP_SBRef--EP--37.json
N14857--cmrr_mb4_bold_566_CBT_Run2_AP_SBRef--EP--37.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run3_AP--EP--42.json
N14857--cmrr_mb4_bold_566_CBT_Run3_AP--EP--42.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run3_AP_SBRef--EP--41.json
N14857--cmrr_mb4_bold_566_CBT_Run3_AP_SBRef--EP--41.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run4_AP--EP--46.json
N14857--cmrr_mb4_bold_566_CBT_Run4_AP--EP--46.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run4_AP_SBRef--EP--45.json
N14857--cmrr_mb4_bold_566_CBT_Run4_AP_SBRef--EP--45.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run5_AP--EP--50.json
N14857--cmrr_mb4_bold_566_CBT_Run5_AP--EP--50.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run5_AP_SBRef--EP--49.json
N14857--cmrr_mb4_bold_566_CBT_Run5_AP_SBRef--EP--49.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run6_AP--EP--54.json
N14857--cmrr_mb4_bold_566_CBT_Run6_AP--EP--54.nii.gz
N14857--cmrr_mb4_bold_566_CBT_Run6_AP_SBRef--EP--53.json
N14857--cmrr_mb4_bold_566_CBT_Run6_AP_SBRef--EP--53.nii.gz
N14857--T1w_MPR_1--GR_IR--7.json
N14857--T1w_MPR_1--GR_IR--7.nii.gz
N14857--T1w_MPR_1--GR_IR--8.json
N14857--T1w_MPR_1--GR_IR--8.nii.gz

**Comment by jmtyszka** [comment]
The list of output files above is from the dcm2niix conversion in the work/ directory. What  do the <BIDS root>/sub-*/.../func and .../fmap directories look like after conversion?

For distortion correction, are you using the SDC functions in fMRIPrep or separate TOPUP or 3dQwarp corrections? SBRef files are T2*-weighted and won't yield accurate distortion correction with TOPUP because of signal dropout. You'd need separate SE-EPI AP/PA images for that which are distorted but have little dropout. If you're using something other than TOPUP, you might want to keep the SBRef images in the func/ folder to be BIDS compliant and update your preprocessing pipeline to look for them there.

**Comment by jawaltz** [comment]
I didn't realize there WAS another folder. Now I see it. Everything looks awesome.

**Comment by jmtyszka** [comment]
Glad it looks good now! Let me know if you have any further questions down the line.
